// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingSubscriptionController from "./booking_subscription_controller"
application.register("booking-subscription", BookingSubscriptionController)

import InsertBookingController from "./insert_booking_controller"
application.register("insert-booking", InsertBookingController)

import MapController from "./map_controller"
application.register("map", MapController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import RestaurantSubscriptionController from "./restaurant_subscription_controller"
application.register("restaurant-subscription", RestaurantSubscriptionController)
